export const authStatus={
		LOGIN_REQUEST:"LOGIN_REQUEST",
		LOGIN_SUCCESS:"LOGIN_SUCCESS",
		LOGIN_FAILED:"LOGIN_FAILED"
}

export const regStatus={
	REG_REQUEST:"REG_REQUEST",
	REG_SUCCESS:"REG_SUCCESS",
	REG_FAILED:"REG_FAILED"
}

export const otpStatus={
    OTP_REQUEST :"OTP_REQUEST",
    OTP_UPDATE:"OTP_UPDATE",
    OTP_SUCCESS :"OTP_SUCCESS",
    OTP_FAILED :"OTP_FAILED"
}
export const generalStatus={
    GENERAL_REQUEST :"GENERAL_REQUEST",
    GENERAL_SUCCESS :"GENERAL_SUCCESS",
    GENERAL_FAILED :"GENERAL_FAILED"
}

export const categoryConstansts={ 
	GET_ALL_CATEGORIES_REQUEST: "GET_ALL_CATEGORIES_REQUEST",
  GET_ALL_CATEGORIES_SUCCESS: "GET_ALL_CATEGORIES_SUCCESS",
  GET_ALL_CATEGORIES_FAILURE: "GET_ALL_CATEGORIES_FAILURE",
  ADD_NEW_CATEGORY_REQUEST: "ADD_NEW_CATEGORY_REQUEST",
  ADD_NEW_CATEGORY_SUCCESS: "ADD_NEW_CATEGORY_SUCCESS",
  ADD_NEW_CATEGORY_FAILURE: "ADD_NEW_CATEGORY_FAILURE",
  UPDATE_CATEGORIES_REQUEST: "UPDATE_CATEGORIES_REQUEST",
  UPDATE_CATEGORIES_SUCCESS: "UPDATE_CATEGORIES_SUCCESS",
  UPDATE_CATEGORIES_FAILURE: "UPDATE_CATEGORIES_FAILURE",
  DELETE_CATEGORIES_REQUEST: "DELETE_CATEGORIES_REQUEST",
  DELETE_CATEGORIES_SUCCESS: "DELETE_CATEGORIES_SUCCESS",
  DELETE_CATEGORIES_FAILURE: "DELETE_CATEGORIES_FAILURE"
}

export const logoutStatus={
    LOGOUT_REQUEST:"LOGOUT_REQUEST",
    LOGOUT_SUCCESS:"LOGOUT_SUCCESS",
    LOGOUT_FAILED:"LOGOUT_FAILED"
}
export const cartStatus = {
  ADD_TO_CART_REQUEST: "ADD_TO_CART_REQUEST",
  ADD_TO_CART_SUCCESS: "ADD_TO_CART_SUCCESS",
  ADD_TO_CART_FAILURE: "ADD_TO_CART_FAILURE",
  RESET_CART: "RESET_CART",

  REMOVE_CART_ITEM_REQUEST: "REMOVE_CART_ITEM_REQUEST",
  REMOVE_CART_ITEM_SUCCESS: "REMOVE_CART_ITEM_SUCCESS",
  REMOVE_CART_ITEM_FAILURE: "REMOVE_CART_ITEM_FAILURE",
};

export const checkStatus={
    CHECK_REQUEST:"CHECK_REQUEST",
    CHECK_SUCCESS:"CHECK_SUCCESS",
    CHECK_FAILED:"CHECK_FAILED"
}


